// backend/scripts/build-public.js
//
// Assembles the folder each per-audience server actually serves:
//   public-<audience>/  =  public-shared/  +  public-<audience>-src/
//
// public-shared/ (currently api.js, products.js) is the single source of
// truth for the handful of files every audience's frontend loads — fix a
// bug there once, and every server's next build picks it up. See the
// multi-domain split plan doc for the full rationale.
//
// Usage: node scripts/build-public.js <customer|seller|admin>
// Run automatically as each Render service's Build Command — see that
// service's config for the exact command. Also safe to run by hand for
// local testing.
//
// public-<audience>/ is regenerated from scratch every run (deleted then
// rebuilt) and is .gitignore'd — never edit files inside it directly, edit
// public-shared/ or public-<audience>-src/ instead. Every .js file copied
// from public-shared/ gets an AUTO-GENERATED banner prepended as a reminder.
const fs = require('fs');
const path = require('path');

const audience = process.argv[2];
if (!['customer', 'seller', 'admin'].includes(audience)) {
  console.error('Usage: node scripts/build-public.js <customer|seller|admin>');
  process.exit(1);
}

const root      = path.join(__dirname, '..', '..'); // bards-new/
const sharedDir = path.join(root, 'public-shared');
const srcDir    = path.join(root, `public-${audience}-src`);
const outDir    = path.join(root, `public-${audience}`);

const BANNER = `/* AUTO-GENERATED — DO NOT EDIT THIS FILE.
   Source of truth: public-shared/%FILE%
   Regenerated automatically on every deploy build. */\n`;

for (const dir of [sharedDir, srcDir]) {
  if (!fs.existsSync(dir)) {
    console.error(`Missing required source folder: ${dir}`);
    process.exit(1);
  }
}

fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

let filesCopied = 0;

function copyTree(from, to, stampBanner) {
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dst = path.join(to, entry.name);
    if (entry.isDirectory()) {
      fs.mkdirSync(dst, { recursive: true });
      copyTree(src, dst, stampBanner);
      continue;
    }
    if (stampBanner && entry.name.endsWith('.js')) {
      const body = fs.readFileSync(src, 'utf8');
      fs.writeFileSync(dst, BANNER.replace('%FILE%', entry.name) + body);
    } else {
      fs.copyFileSync(src, dst);
    }
    filesCopied++;
  }
}

copyTree(sharedDir, outDir, true);  // api.js, products.js — banner stamped
copyTree(srcDir, outDir, false);    // audience-specific pages — untouched

console.log(`Built public-${audience}/ (${filesCopied} files) from public-shared/ + public-${audience}-src/`);
